# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cglram <- function(tnsr, ranks, lambda, L0_, D, tol, max_iter) {
    .Call(`_SmoothHOOI_cglram`, tnsr, ranks, lambda, L0_, D, tol, max_iter)
}

mglram <- function(tnsr, ranks, lambda, L0_, D, tol = 1e-5, max_iter = 500L, init = 0) {
    .Call(`_SmoothHOOI_mglram`, tnsr, ranks, lambda, L0_, D, tol, max_iter, init)
}

oracle <- function(tnsr, smooth_tnsr, rank_grid, lambda_seq, L0_, D, tol = 0.1, max_iter = 500L, init = 0) {
    .Call(`_SmoothHOOI_oracle`, tnsr, smooth_tnsr, rank_grid, lambda_seq, L0_, D, tol, max_iter, init)
}

kcv <- function(tnsr, rank_grid, lambda_seq, k, L0_, D, tol = 0.1, max_iter = 500L, init = 0) {
    .Call(`_SmoothHOOI_kcv`, tnsr, rank_grid, lambda_seq, k, L0_, D, tol, max_iter, init)
}

loss <- function(tnsr, smooth_tnsr, L, true_L, R, true_R) {
    .Call(`_SmoothHOOI_loss`, tnsr, smooth_tnsr, L, true_L, R, true_R)
}

